// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb9QJYxU7zmt1atubf6FogIzM-9lD5FdA',
    appId: '1:738201020981:web:df3f76a83906ae9360df7c',
    messagingSenderId: '738201020981',
    projectId: 'reiminkzwembadenadmin',
    authDomain: 'reiminkzwembadenadmin.firebaseapp.com',
    storageBucket: 'reiminkzwembadenadmin.appspot.com',
    measurementId: 'G-RK6M448X8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxSV6Rz2hUwiumCDivde8kjuDSsQxyCs',
    appId: '1:738201020981:android:4e33999736b0229b60df7c',
    messagingSenderId: '738201020981',
    projectId: 'reiminkzwembadenadmin',
    storageBucket: 'reiminkzwembadenadmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbNUqM03eqlcHtoTfEhgzCj8IkfhL7zk',
    appId: '1:738201020981:ios:d3c8ff04dc36db6f60df7c',
    messagingSenderId: '738201020981',
    projectId: 'reiminkzwembadenadmin',
    storageBucket: 'reiminkzwembadenadmin.appspot.com',
    iosClientId: '738201020981-99df87i7qiav6ta6rrsftchodab56r3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.reiminkZwembadenAdmin',
  );
}
